### ISSUE TITLE
Remove calendar:start from config.yaml

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-esm1.6-configs#91]
This section in `config.yaml` has [no effect](https://github.com/search?q=repo%3Apayu-org%2Fpayu+config%5B%27calendar%27%5D&type=code), and could be removed:

```
    start:
        year: 101
        month: 1
        days: 1
```

In the esm1.6 configurations, we are mostly (always?) starting from existing restart files, so the start year comes from the restart files.
